services:
  # 1. Le moteur PHP (L'API Symfony)
  api:
    build: .
    container_name: symfony_api
    restart: always
    volumes:
      - .:/var/www/symfony
    env_file:
      - .env
    # Permet au conteneur Docker de voir le "localhost" de votre PC Windows (XAMPP)
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # 2. Le serveur Web Nginx
  webserver:
    image: nginx:alpine
    container_name: symfony_webserver
    restart: always
    ports:
      - "8000:80" # Votre API Symfony sera disponible sur http://localhost:8000
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api